### ISSUE TITLE
Definition Of Done Checklist

### ISSUE THREAD

**Issue by tedpennington** [c-cannons/bangazon-api#14]
- [ ] Complete README that documents the steps to install the code, how to install any dependencies, or system configuration needed.

- [ ] Every class must be documented with purpose, author, and methods.

- [ ] Every method must be documented with purpose and argument list - which itself must contain a short purpose for each argument.

- [ ] The project must be able to run fully, and without errors, on each teammate's system.

- [ ] Fulfills every requirement.

- [ ] Every line of code has been peer reviewed.

- [ ] For projects that require unit testing, core functionality must be identified and have at least one test for each.
